<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials" tests="7" time="0.010" ignored="0" failures="0" timestamp="16 Dec 2017 13:30:01 GMT" skipped="6" hostname="Deepak" errors="1">
  <testcase name="verify_login_with_invalid_credentials" time="0.003" classname="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verify_login_with_invalid_credentials -->
  <testcase name="verify_login_with_invalid_credentials" time="0.002" classname="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verify_login_with_invalid_credentials -->
  <testcase name="verify_login_with_invalid_credentials" time="0.001" classname="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verify_login_with_invalid_credentials -->
  <testcase name="verify_login_with_invalid_credentials" time="0.001" classname="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verify_login_with_invalid_credentials -->
  <testcase name="setup" time="0.000" classname="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials">
    <error type="org.openqa.selenium.SessionNotCreatedException" message="Failed to start browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe: other os error
Build info: version: &#039;3.4.0&#039;, revision: &#039;unknown&#039;, time: &#039;unknown&#039;
System info: host: &#039;DEEPAK&#039;, ip: &#039;192.168.1.101&#039;, os.name: &#039;Windows 8.1&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.3&#039;, java.version: &#039;1.8.0_121&#039;
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4821c4 - &lt;no info&gt;
   1:           0x482933 - &lt;no info&gt;
   2:           0x445159 - &lt;no info&gt;
   3:           0x44cbd2 - &lt;no info&gt;
   4:           0x43026a - &lt;no info&gt;
   5:           0x40ba4e - &lt;no info&gt;
   6:           0x4119b9 - &lt;no info&gt;
   7:           0x6d2c89 - &lt;no info&gt;
   8:           0x426006 - &lt;no info&gt;
   9:           0x6cd490 - &lt;no info&gt;
  10:     0x7ffc647313d2 - BaseThreadInitThunk">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Failed to start browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe: other os error
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DEEPAK', ip: '192.168.1.101', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4821c4 - <no info>
   1:           0x482933 - <no info>
   2:           0x445159 - <no info>
   3:           0x44cbd2 - <no info>
   4:           0x43026a - <no info>
   5:           0x40ba4e - <no info>
   6:           0x4119b9 - <no info>
   7:           0x6d2c89 - <no info>
   8:           0x426006 - <no info>
   9:           0x6cd490 - <no info>
  10:     0x7ffc647313d2 - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
	at com.Servcorp.testBase.TestBase.select_browser(TestBase.java:119)
	at com.Servcorp.testBase.TestBase.init(TestBase.java:102)
	at com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials.setup(TC002_VerifyLoginWithInvalidCredentials.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase name="verify_login_with_invalid_credentials" time="0.002" classname="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verify_login_with_invalid_credentials -->
  <testcase name="verify_login_with_invalid_credentials" time="0.001" classname="com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verify_login_with_invalid_credentials -->
</testsuite> <!-- com.Servcorp.HomePage.TC002_VerifyLoginWithInvalidCredentials -->
